### ISSUE TITLE
Running line

### ISSUE THREAD

**Issue by roman-koshchei** [flurium/spentoday-shop#41]
Сделать ету строку бегущей, как бегущая строка в лендинге:

![Image](https://github.com/flurium/spentoday-shop/assets/103932583/a54d6003-2942-4754-ae0b-e6c88783b4dd)

Фрази ето массив строк. Тестируй как на десктопе, так и на мобиле.

![Image](https://github.com/flurium/spentoday-shop/assets/103932583/a5ec6158-35de-4379-a877-1efba1152b2c)

**Comment by vitalii-lytvynenko** [comment]
Resolved
